spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: Corretora de Seguros
  banner:
    location: classpath:bann.txt
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
arlepton:
  features:
    cache:
      enable: ${ARLEPTON_FEATURES_ENABLE_CACHE:false}
    cors:
      enable: ${ARLEPTON_FEATURES_ENABLE_CORS:true}
      allowedOrigins: ${ARLEPTON_FEATURES_ALLOWED_ORIGINS:http://localhost:5000, http://arlepton.com, http://localhost:8080}
    email:
      enable: ${ARLEPTON_FEATURES_EMAIL_ENABLE:true}
      protocol: ${ARLEPTON_FEATURES_EMAIL_PROTOCOL:smtp}
      host: ${ARLEPTON_FEATURES_MAIL_HOST:smtp.gmail.com}
      port: ${ARLEPTON_FEATURES_MAIL_PORT:587}
      username: ${ARLEPTON_FEATURES_MAIL_USERNAME:finhat2@gmail.com}
      password: ${ARLEPTON_FEATURES_MAIL_PASSWD:lmgxinxclovehtfp}
      debug: ${ARLEPTON_FEATURES_MAIL_DEBUG:true}
      recovery-password:
        domain: ${ARLEPTON_FEATURES_MAIL_RESET_DOMAIN:http://localhost:3001}
        token-ttl-minutes: ${ARLEPTON_FEATURES_MAIL_RESET_TOKEN:1}
      smtp:
        auth: true
        starttls:
          enable: true
          require: true
    security:
      enable: 
      # valores possíveis: oauth2, internal, none
      mode: internal
      internal:
        timeZoneId: America/Montevideo
        expirationInSecondsToken: 360
        expirationInSecondsRefreshToken: 720
      oauth2:
        issuer: ${OID_ISSUER_URL:https://oid.clibano.io/realms/arlepton}
        algorithm: ${OID_ISSUER_ALGORITHM:RSA}
        publicKey: ${OID_ISSUER_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxI0aU3pVwUawoxMHSEI9s1wEc0XOLMUdxZOXjqwKFTupegFLt1x/HdBgFfChuhvu+u2KkGLYHpVoKxpRuTZf/7wnBPZrRzQ1OIkeQAbPlGdUlWgXtBAkYumGquFgUCF6+0i4Z9VzpoVOosA8Q4mQIeUkybUrywFlAgLL0PMKC9eG3z93Cz9Mtc1Z0bALcT5pfHYQ69VXYdrJeq8ZTuj4OaKGV8a/Cxp9HTT3wz0j3P/9wQIMEM8CkXS2drfuRTOOHLAXS6JjR3ZXUhG9m/xBpwKYS7Ydc0913di83ICurnLoIhRkpGaoVtSRM/6gceqyr4Aj2ZmGeufU/N0zgyeYAQIDAQAB}

openapi:
  service:
    title: Finner's Bank API
    version: 1.0.0

springdoc:
  swagger-ui:
    enabled: true
  show-actuator: false
  packagesToScan: com.amran.dynamic.multitenant.controller

server:
  compression:
    enabled: true
  port: 8080
  servlet: 
    context-path: /
    
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

multitenancy:
  mtapp:
    master:
      datasource:
        platform: postgresql
        url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:arlepton1234}
        driverClassName: org.postgresql.Driver
        connectionTimeout: 20000
        maxPoolSize: 250
        idleTimeout: 300000
        minIdle: 5
        poolName: masterdb-connection-pool
      jpa:
        hibernate:
          ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
          hibernate:
            multiTenancy: DATABASE
            jdbc:
              lob:
                non_contextual_creation: true
logging:
  level:
    root: INFO
    com.amran.dynamic.multitenant: INFO
    org.springframework.boot.context: INFO